version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - pip install mkdocs
      - pip install mkdocs-material
    build:
      # 用适当的构建类型替换 'commands'
      type: html  # 指定构建目标类型为 HTML
      commands:
        - mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml
