version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install mkdocs
      - pip install mkdocs-material
    build:
      type: html
    # 如需自定义命令，可定义其他阶段
    pre_build:
      - echo "Running pre build commands"
