version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - pip install mkdocs mkdocs-material
    commands:
      - mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml
mkdocs:
  configuration: mkdocs.yml
