version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - pip install mkdocs
      - pip install mkdocs-material
    build:
      # 直接使用 commands 数组来指定构建命令
      commands:
        - mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml
